### ISSUE TITLE
Sync with upstream changes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agronholm/pythonfutures#19]
```
The concurrent.futures module in cpython has had some changes since this 
backport was released; it would be good to sync up with cpython 3.3.  I'm 
particularly interested in this change:
  http://hg.python.org/cpython/annotate/4390d6939a56/Lib/concurrent/futures/thread.py#130
which prevents a 100ms delay when shutting down a ThreadPoolExecutor.
```

Original issue reported on code.google.com by `ben.darn...@gmail.com` on 23 May 2013 at 3:28

**Comment by harlowja** [comment]
:+1:  to this, there have been some changes that have been flushing through upstream to fix bugs that would be great to have incorporated here (if they haven't already been).

- https://bugs.python.org/issue9205
- https://bugs.python.org/issue16284
- https://bugs.python.org/issue22393
- https://bugs.python.org/issue21362
- others?

**Comment by agronholm** [comment]
Issue 21362 is the only one that is actually fixable -- the rest have either been fixed already or unfixable due to upstream code using py3 specific features.

**Comment by agronholm** [comment]
I'm closing this as wontfix because 21362 has been fixed here already and the rest are not fixable.
