### ISSUE TITLE
child processes inherit parent's global state?

### ISSUE THREAD

**Issue by mariusnita** [agronholm/pythonfutures#48]
Hi,

```python
import concurrent.futures as cf

BEEP = None

def foo(x):
    print BEEP

if __name__ == '__main__':
    BEEP = 500
    with cf.ProcessPoolExecutor(max_workers=4) as executor:
        for i in xrange(10):
            executor.submit(foo, i)
```

In this example, I would expect all the processes to print `None`, but they all print `500`. Is this the correct behavior?

If so, is there a way to exec clean processes without inheriting memory from the parent?

**Comment by agronholm** [comment]
On non-Windows platforms, multiprocessing.Process forks the child from the parent process. That means the memory is copied over. There is no way to make multiprocessing.Process work any other way.

**Comment by mariusnita** [comment]
That makes sense, thanks. Maybe a workaround is for the child process to run an `init` function that resets the global state.

**Comment by agronholm** [comment]
Or to not rely on global state to begin with.
