### ISSUE TITLE
ThreadPoolExecutor should have a default value of None for the max_workers argument

### ISSUE THREAD

**Issue by jbg** [agronholm/pythonfutures#54]
https://docs.python.org/dev/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

**Comment by agronholm** [comment]
This was a change made only in the latest version of Python 3. While the change is trivial, this backport only covers 3.2 level features anyway, as some changes made to it upstream after 3.2 are impossible to implement here.

**Comment by agronholm** [comment]
Fixed in 09138538e446dbe7664bfab5b29fd2d51e625d4d.
