### ISSUE TITLE
 issue with proxy authentication when installing the package "futures: 3.0.5" ("futures 3.0.3" seems to works fine)

### ISSUE THREAD

**Issue by tarrade** [agronholm/pythonfutures#56]
Hi there,

Not sure what is the best place to post this. Please tell me if this is not the right place.

I installed conda 3.18.8 (My company used this version) on a PC (Windows 7):

H:\>conda info
Current conda install:
             platform : win-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.8.1
     root environment : C:\Program Files\Anaconda2  (writable)
  default environment : C:\Program Files\Anaconda2
     envs directories : C:\Program Files\Anaconda2\envs
        package cache : C:\Program Files\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\C172685\.condarc
    is foreign system : False

with a condarc file for the proxy config and with the following packages:

pip
scipy
cx_oracle
anaconda-navigator
blaze
conda-manager
dill
et_xmlfile

which gave me
anaconda                  2.4.1
conda                       4.1.11

when I install "futures: 3.0.5-py27_0 defaults" I get an issue with the proxy (see screenshot 1)
![screenshot 1](https://cloud.githubusercontent.com/assets/12021701/17329454/030095d6-58c3-11e6-9fc7-b59fb0024506.png)

as you ca see it asked for "https proxy username: Password:"
-> I can see all the character when I type the pwd
-> the pwd doesn't work
-> it will ask me again the pwd and then it will be stuck and I will have to kill the windows ! 

I thought it was an issue with the proxy with our company but if I removed it it works fine again (no issue with the pwd) !(see screenshot 2)
![screenshot 2](https://cloud.githubusercontent.com/assets/12021701/17329500/2fb99e24-58c3-11e6-8801-696504ed9c33.png)

I also find that: futures  3.0.3 works fine
Do expert understand my issue with futures: 3.0.5-py27_0 defaults ? Why it affect the authentication with the proxy ?

I am new with conda and almost now knowledge with proxy.

Thanks a lot
Cheers
Fabien

**Comment by agronholm** [comment]
I have no idea what this problem of yours has to do with the futures library. This seems like a Conda related problem so it's best you complain about it to the Conda folks. If you can show me a problem that does not involve Conda, then post a message here and I will reopen this issue.

**Comment by tarrade** [comment]
ok, I will check with Conda folks. Thanks
