### ISSUE TITLE
Backport: Issue #27664: Allow specifying prefix for thread name in concurrent.futures.ThreadPoolExecutor

### ISSUE THREAD

**Issue by normanr** [agronholm/pythonfutures#63]
Please consider including the changes for thread_name_prefix:

http://bugs.python.org/issue27664, commit: https://github.com/python/cpython/commit/50abe877ee6f50ebd9cfe228d314220e071fa3c6

**Comment by dhermes** [comment]
@agronholm Any idea when this will make it in a release?

**Comment by agronholm** [comment]
I can make a new release any time. Nothing else is in the pipeline for this project right now so I don't mind.

**Comment by dhermes** [comment]
That would be great!

**Comment by agronholm** [comment]
Right, I had forgotten about https://github.com/agronholm/pythonfutures/pull/66
I'd like to get this in too, just needs a little bit of review first.

**Comment by agronholm** [comment]
I've released v3.2.0 now.

**Comment by dhermes** [comment]
Thanks!
