### ISSUE TITLE
dill instead of pickle

### ISSUE THREAD

**Issue by runflowcode** [agronholm/pythonfutures#74]
Hi

Would it be possible to use dill instead of pickle for your queues ? Dill is a better alternative for serialization than pickle. 

https://stackoverflow.com/questions/8804830/python-multiprocessing-pickling-error

**Comment by agronholm** [comment]
I think there is a misunderstanding here. This is a backport of the `concurrent.futures` standard library module, like it says in the README. So it will never have any features not found in its standard library counterpart.
