### ISSUE TITLE
Update PyPi please

### ISSUE THREAD

**Issue by j-walker23** [agronholm/pythonfutures#76]
`pip install futures==3.2.0`

Collecting futures==3.2.0
  Could not find a version that satisfies the requirement futures==3.2.0 (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
No matching distribution found for futures==3.2.0

Originating from https://github.com/pypa/pipenv/issues/1579.

**Comment by agronholm** [comment]
Release 3.2.0 has been on PyPI for ages as you can see [here](https://pypi.org/project/futures/3.2.0/#files). Is there a chance you are mistakenly installing it on Python 3?

**Comment by j-walker23** [comment]
Yep, you are right, i am 100% trying on python3.

I don't actually need this dep. It just happens to be in `google-cloud` which i depend on and it is correctly set for only python 2.7 in https://github.com/GoogleCloudPlatform/google-cloud-python/blob/e107bae4047f6e2df415dce155a67405ab11a205/api_core/setup.py.

So that all seems right. But if you look at the issue i referenced in my original comment from `kennethreitz` he mentioned the `setup.py` in this repo was the issue. Before i go back there are their any known issues in this repos `setup.py` that he might be referring too?

Also, thanks for the quick reply! Really appreciated.

**Comment by agronholm** [comment]
There are no issues that I'm aware. The distribution should not be installable at all on Python 3 and I've made every effort to that end.

**Comment by j-walker23** [comment]
Thanks, i appreciate the help!

**Comment by j-walker23** [comment]
Just an update with this. The issue was not on this lib, which i'm sure you already knew. Thanks for helping me narrow down the cause.
