### ISSUE TITLE
3.1.2 does not specify Requires-Python

### ISSUE THREAD

**Issue by Alphadelta14** [agronholm/pythonfutures#82]
A new error was added to this package when installing on Python 3. However, most versions of this package have some sort of `Requires-Python: >=2.6, <3` in their PKG-INFO / metadata corresponding to `python_requires='>=2.6, <3',` in setup.py. Unfortunately, the 3.1.2 version of this package does not, so it fails miserably.

**Comment by Alphadelta14** [comment]
I guess this is kinda the point, huh.
If any version of this is getting installed on Python 3, then it's liable to break things. So force people to use a platform specifier to just not install futures when on python 3.

**Comment by agronholm** [comment]
Yeah, see #81 for discussion on why this release was made.
