### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by TianMingChen** [agronholm/pythonfutures#85]
![图片](https://user-images.githubusercontent.com/20785298/56456853-bab94080-63a4-11e9-8d38-796513dbdf81.png)
how to solve this prolem?

**Comment by agronholm** [comment]
Remove `pythonfutures` from your `PYTHONPATH`. It has no business being installed on Python 3.

**Comment by TianMingChen** [comment]
> Remove `pythonfutures` from your `PYTHONPATH`. It has no business being installed on Python 3.

But how to remove `pythonfutures` from PYTHONPATH?
when I import torch,it also has problem?
![image](https://user-images.githubusercontent.com/20785298/56469096-9bcfb280-6467-11e9-9166-e1df7b4ad1b5.png)

**Comment by agronholm** [comment]
I do not know how you installed it, but you must uninstall it. Perhaps using `pip uninstall futures` ?
