### ISSUE TITLE
Each time set_result/set_exception/set_exception_info is invoked, done callbacks are executed repeatedly

### ISSUE THREAD

**Issue by tim-chow** [agronholm/pythonfutures#86]
below is an example:
<pre>
from concurrent.futures import Future

def done_callback(f):
    print("done callback is invoked")

f = Future()
f.add_done_callback(done_callback)
f.set_result('first set')
f.set_result('second set')
</pre>
the output is:
<pre>
done callback is invoked
done callback is invoked
</pre>

I think that future can only be set once, it's better. and in this case, done callbacks will be invoked only once.
<pre>
class Future(object):
    ...
    def set_result(self, result):
        """Sets the return value of work associated with the future.
        Should only be used by Executor implementations and unit tests.
        """
        with self._condition:
            if self.done():
                return
            ...

    def set_exception_info(self, exception, traceback):
        """Sets the result of the future as being the given exception
        and traceback.
        Should only be used by Executor implementations and unit tests.
        """
        with self._condition:
            if self.done():
                return
            ...
</pre>

**Comment by agronholm** [comment]
This is how it works in the upstream implementation (even in 3.7). This is just a backport so I'm not going to do anything about this.
