### ISSUE TITLE
fail to transfer some div in function

### ISSUE THREAD

**Issue by BichengWang** [agronholm/pythonfutures#87]
python2 code:
```
def integer_time(ms):
    return ms / 60 * 60
```
```futurize -w --stage2```fail to detect these kinds of div.
It should become following format in python3
```
def integer_time(ms):
    return old_div(ms, 60) * 60
```

**Comment by agronholm** [comment]
Sorry but what does this have to do with futures?

**Comment by agronholm** [comment]
No explanation given in 2 weeks, probably filed against the wrong project – closing.
