### ISSUE TITLE
Declare python_requires<3 in setup.py?

### ISSUE THREAD

**Issue by atugushev** [agronholm/pythonfutures#95]
See https://github.com/pypa/setuptools/issues/2687#issuecomment-939064397 for details.

**Comment by agronholm** [comment]
I should also point out that this is already present in setup.py: https://github.com/agronholm/pythonfutures/blob/master/setup.py#L39

**Comment by atugushev** [comment]
Ah, I should've checked the latest `setup.py` in the first place. Sorry for the noise!
